import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="App">
        <nav id={styles.navbar}>
          <div>
            <a href="#welcome-section" className={styles.navElements}>
              About
            </a>
            <a href="#project-title" className={styles.navElements}>
              Work
            </a>
            <a href="#contact-section" className={styles.navElements} id="profile-link">
              Contact
            </a>
          </div>
        </nav>
        <section id={styles.welcomeSection}>
          <h1>Hello i'm Pedro</h1>
          <p id={styles.welcomeP}>A student who like web development</p>
        </section>
        <section id={styles.projects}>
          <h1 id={styles.projectTitle}>These are some of my projects</h1>
          <div id={styles.project}>
            <div className={`${styles.project} ${styles.hidden}`} id={styles.gridItem1}>
              <Image
                src="/img/tsla.png"
                alt="Project"
                width={300}
                height={400}
                className={styles.projectImg}
              />
              <a
                href="https://pedroddjkkk.github.io/TributePage/"
                className={styles.projectTile}
              >
                Tribute Page
              </a>
            </div>
            <div className={`${styles.project} ${styles.hidden}`} id={styles.gridItem2}>
              <Image
                src="/img/survey.png"
                alt="Project"
                width={300}
                height={400}
                className={styles.projectImg}
              />
              <a
                href="https://pedroddjkkk.github.io/SurveyForm/"
                className={styles.projectTile}
              >
                Survey Form
              </a>
            </div>
            <div className={`${styles.project} ${styles.hidden}`} id={styles.gridItem3}>
              <Image
                src="/img/prduct.png"
                alt="Project"
                width={300}
                height={400}
                className={styles.projectImg}
              />
              <a
                href="https://pedroddjkkk.github.io/ProductPage/"
                className={styles.projectTile}
              >
                Product Page
              </a>
            </div>
            <div className={`${styles.project} ${styles.hidden}`} id={styles.gridItem4}>
              <Image
                src="/img/calculator.png"
                alt="Project"
                width={300}
                height={400}
                className={styles.projectImg}
              />
              <a
                href="https://pedroddjkkk.github.io/CalculadoraReact/"
                className={styles.projectTile}
              >
                React Calculator
              </a>
            </div>
          </div>
        </section>
        <section id="contact-section">
          <div className="contact-links">
            <a
              id="profile-link"
              href="https://github.com/pedroddjkkk"
              target="_blank"
              className="contact-details"
            >
              <i className="fab fa-github"></i> GitHub
            </a>
            <a
              href="https://twitter.com/pedroddjkk"
              target="_blank"
              className="contact-details"
            >
              <i className="fab fa-twitter"></i> Twitter
            </a>
            <a href="malito: pedroddjkk@gmail.com" className="contact-details">
              <i className="fas fa-at"></i> Send a mail
            </a>
            <a href="tel:+55-44-997506602" className="contact-details">
              <i className="fas fa-mobile-alt"></i> Call me
            </a>
          </div>
        </section>
      </div>
    </>
  );
}
